name: Build Workflow
on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
      resource:  
        required: false
        type: string
      java-version:
        required: false
        type: string
        default: '11'
      # allowing calling workflows to pass in maven parameter(s) such as '-Dmaven.test.skip' for certain apps, default to blank, not to skip test
      maven-params:
        required: false
        type: string
        default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.resource }} 

    steps:
     - uses: actions/checkout@v3
     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
         java-version: '11'
         distribution: 'temurin'
         server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
         settings-path: ${{ github.workspace }} # location for the settings.xml file

     - name: Build with Maven
       run: mvn -B package --settings $GITHUB_WORKSPACE/settings.xml --file pom.xml
       env:
        GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
        GITHUB_TOKEN: ${{ github.token }}
