name: Build Workflow
on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
      resource:  
        required: false
        type: string
      java-version:
        required: false
        type: string
        default: '11'
      # allowing calling workflows to pass in maven parameter(s) such as '-Dmaven.test.skip' for certain apps, default to blank, not to skip test
      maven-params:
        required: false
        type: string
        default: ''
jobs:
  lint-codebase:
    name: Lint Code Base
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.resource }} 
    steps:
     - name: Checkout Code
       uses: actions/checkout@v3
       with:
         fetch-depth: 0

     - uses: github/super-linter/slim@v4
       env:
         VALIDATE_ALL_CODEBASE: false
         DEFAULT_BRANCH: ${{ github.head_ref }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         VALIDATE_JAVA: true
         DISABLE_ERRORS: true
  
  build-feature:
    name: build project
    needs: lint-codebase
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.resource }} 
    steps:
      - uses: actions/checkout@v2
      - name: Checkout folder source code from ${{ github.head_ref }} for the event ${{ github.event_name }}
        run: |
          echo "Checkout folder ${{ inputs.resource }}"
      - name: Setup jdk
        uses: actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean install ${{ inputs.maven-params }} --file pom.xml

  complete:
    # see https://github.community/t/status-check-for-a-matrix-jobs/127354/7
    name: Complete CI
    needs: build-feature
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check all job status
        # see https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#needs-context
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
        run: exit 1