name: Maven Package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/release-please-action@v3
      with:
       release-type: maven
       
