name: Maven Package

on:
  push:
    branches:
      - test-qua

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
   
