name: Eden build

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    branches:
      - main
    paths:
      - 'lambda1/**'
      - 'lambda2/**'
jobs:
  activate-workflow:  
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    outputs:
      # Expose matched filters as job 'projects' output variable
      projects: ${{ steps.filter.outputs.changes }}
    steps:
     - uses: actions/checkout@v2
       with:
         fetch-depth: 0
     - uses: dorny/paths-filter@v2
       id: filter
       with:
         list-files: json
         filters: |
           lambda1:
             - 'lambda1/**'
           lambda2:
             - 'lambda2/**'
  build:
    needs: activate-workflow 
    strategy:
      matrix:
        # Parse JSON array containing names of all filters matching any of changed files
        # e.g. ['package1', 'package2'] if both package folders contains changes
        projects: ${{ fromJSON(needs.activate-workflow.outputs.projects) }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ (matrix.projects) }}
    steps:
      - uses: actions/checkout@v3
      - name: Checkout folder source code from ${{ github.head_name }} for the event ${{ github.event_name }}
        run: |
          echo "Checkout folder ${{ (matrix.projects) }} "
      - name: Setup jdk
        uses: actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc
        with:
          java-version: 11
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean install --file pom.xml  
 

  
 

