name: Eden Deploy

on:
  pull_request:
    branches: 
      - test-qua
    types: [closed]

jobs:
  activate-workflow:
    runs-on: ubuntu-latest
    # Required permissions
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    permissions:
      pull-requests: read
    outputs:
      # Expose matched filters as job 'projects' output variable
      projects: ${{ steps.filter.outputs.changes }}
    steps:
     - uses: actions/checkout@v3
     - uses: dorny/paths-filter@v2
       id: filter
       with:
         list-files: json
         filters: |
           lambda1:
             - 'lambda1/**'
           lambda2:
             - 'lambda2/**'
  deploy-to-eden:
    needs: activate-workflow
    if: ${{ needs.activate-workflow.outputs.projects != '[]' }}
    strategy:
      matrix:
        projects: ${{ fromJSON(needs.activate-workflow.outputs.projects) }}
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      stage: ${{ github.ref_name }}
      resource: ${{ (matrix.projects) }}  
  complete:
    # see https://github.community/t/status-check-for-a-matrix-jobs/127354/7
    name: Complete Eden Deploy
    needs: deploy-to-eden
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check all job status
        # see https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#needs-context
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{
                contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
        run: exit 1
  
 

