name: Eden build

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    branches:
      - test-qua
    paths:
      - 'lambda1/**'
      - 'lambda2/**'
jobs:
 
  lint-pull-request:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Install Dependencies
       run: npm install @commitlint/config-conventional
     - uses: JulienKode/pull-request-name-linter-action@v0.5.0
     - name: Create comment
       uses: peter-evans/create-or-update-comment@v2
       id: create-comment
       with:
         issue-number:  ${{ github.event.pull_request.number }}
         body: |
           Github [Bot] approves this comment
         reactions: rocket
  activate-workflow:  
    runs-on: ubuntu-latest
    needs: lint-pull-request
    # Required permissions
    permissions:
      pull-requests: read
    outputs:
      # Expose matched filters as job 'projects' output variable
      projects: ${{ steps.filter.outputs.changes }}
    steps:
     - uses: actions/checkout@v3
     - uses: dorny/paths-filter@v2
       id: filter
       with:
         list-files: json
         filters: |
           lambda1:
             - 'lambda1/**'
           lambda2:
             - 'lambda2/**'
  security-scan:
    needs: activate-workflow
    if: ${{ needs.activate-workflow.outputs.projects != '[]' }}
    strategy:
      matrix:
        projects: ${{ fromJSON(needs.activate-workflow.outputs.projects) }}
    uses: ./.github/workflows/security-scan.yml
    with:
      stage: ${{ github.ref_name }}
      resource: ${{ (matrix.projects) }}
  triage:
    name: Label pull rquest
    needs: security-scan
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
  
  auto-approve:
    runs-on: ubuntu-latest
    needs: security-scan
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          review-message: "Auto approved automated PR"
  auto-merge:
    runs-on: ubuntu-latest
    name: Auto-merge Bot
    needs: auto-approve
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
      
    
  
  deploy-to-eden:
    needs: [activate-workflow, auto-merge]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh workflow run Eden-deploy.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
    
  complete:
    # see https://github.community/t/status-check-for-a-matrix-jobs/127354/7
    name: Complete Security Scan
    needs: [lint-pull-request, activate-workflow, security-scan, triage, auto-approve, auto-merge,deploy-to-eden]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check all job status
        # see https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#needs-context
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{
                contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
        run: exit 1
  
 

