name: Eden Deploy

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    branches:
      - main
    paths:
      - 'lambda1/**'
      - 'lambda2/**'
jobs:
  activate-workflow:  
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.extract_branch.outputs.branch }}
    steps:
     - uses: actions/checkout@v2
       with:
         fetch-depth: 0
     - uses: dorny/paths-filter@v2
       id: filter
       with:
         list-files: json
         filters: |
           lambda1:
             - 'lambda1/**'
           lambda2:
             - 'lambda2/**'
     - name: Extract branch name
       id: extract_branch 
       shell: bash
       run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
                 
  detecting-changes:
    name: REF NAME VALUE - ${{ github.head_ref }}
    needs: activate-workflow 
    runs-on: ubuntu-latest
    steps: 
      - run: echo ${{ needs.changes.outputs.names }}    

  
 

